config/routes.rb
Unternship::Application.routes.draw do

  resources :applicants

  resources :tasks
  
  resources :assignments

  root :to => 'pages#home'
  
  get '/admin' => 'pages#admin', as: :admin
  
  get '/about' => 'pages#about', as: :about
  
  post '/assignment_update' => 'assignments#assignment_update', as: :assignment_update
  
  get '/assignment_profile/:id' => 'assignments#profile', as: :assignment_profile
  
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  
  attr_accessible :content, :current_role, :email, :job_seeker, :name, :task_id
  attr_accessor :task_id
  
  #Associations
  has_many :assignments
  
  #Instance Method
  def formatted_job_seeker
    job_seeker ? 'Yes' : 'No'
  end
    
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  
  #Attributes
  attr_accessible :applicant_id, :rating, :review, :task_id, :accepted, :completed
  attr_accessor :completed
  
  #Associations
  belongs_to :applicant
  belongs_to :task
  
  #Callback
  after_save :mark_complete_associated_task
  
  #Instance Method
  
  def email
    applicant.email
  end
  
  def mark_complete_associated_task
    if self.completed
      self.task.update_attribute(:completed, true)
    end
  end
  
  def id_and_email
    "#{id} - #{applicant.email}"
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  
  #Attributes
  attr_accessible :contact_name, :deadline, :details, :email, :organization_description, :organization_name, :organization_url, :title,
              :file, :completed
  
  #Associations
  has_many :assignments
  
  #Validation
  validates :organization_name, :organization_url, :contact_name, :email, :organization_description, :title, :deadline, :details, presence: true
  
  #Scope
  scope :incomplete_first, order('completed DESC')
  
  #Uploader
  mount_uploader :file, FileUploader

  
  #Instance Methods
  def formated_organization_url
    if organization_url.match(/http(s*):\/\//).present?
      organization_url
    else
      "http://#{organization_url}"
    end
  end
  
  def formatted_deadline
    deadline.present? ? deadline.strftime('%D') : nil
  end
  
  def assigned?
    assignments.where(accepted: true).length > 0
  end
  
  def not_assigned?
    !assigned?
  end
  
  def accepted_assignment
    assignments.where(accepted: true).first
  end
  
  def self.unassigned
    self.order('created_at DESC').keep_if { |task| task.not_assigned? }
  end
  
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  # # GET /applicants
  # # GET /applicants.json
  # def index
  #   @applicants = Applicant.all
  # 
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @applicants }
  #   end
  # end
  # 
  # # GET /applicants/1
  # # GET /applicants/1.json
  # def show
  #   @applicant = Applicant.find(params[:id])
  # 
  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @applicant }
  #   end
  # end
  # 
  # # GET /applicants/new
  # # GET /applicants/new.json
  # def new
  #   @applicant = Applicant.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @applicant }
  #   end
  # end
  # 
  # # GET /applicants/1/edit
  # def edit
  #   @applicant = Applicant.find(params[:id])
  # end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(params[:applicant])
    @assignment = @applicant.assignments.build(task_id: @applicant.task_id, accepted: false)

    respond_to do |format|
      if @applicant.save
        SiteMailer.new_applicant(@applicant, @assignment).deliver
        format.html { redirect_to tasks_url, notice: 'Thanks for applying! You should receive an email confirmation soon.' }
        format.json { render json: @applicant, status: :created, location: @applicant }
      else
        format.html { render action: "new" }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PUT /applicants/1
  # # PUT /applicants/1.json
  # def update
  #   @applicant = Applicant.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @applicant.update_attributes(params[:applicant])
  #       format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @applicant.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # DELETE /applicants/1
  # # DELETE /applicants/1.json
  # def destroy
  #   @applicant = Applicant.find(params[:id])
  #   @applicant.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to applicants_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  
  def assignment_update
    
    @assignment = Assignment.find(params[:assignment][:id])
    
    respond_to do |format|
      if @assignment.update_attributes(accepted: true)
        format.html { redirect_to admin_url }
      end
    end
    
  end
  
  def show
    @assignment = Assignment.find(params[:id], include: [:task, :applicant])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end
  
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to admin_url }
        format.json { head :no_content }
      end
    end
  end
  
  def profile
    @assignment = Assignment.find(params[:id], include: [:task, :applicant])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  http_basic_authenticate_with :name => "admin", :password => "unternship", :only => :admin
  
  def home
    
  end
  
  def about
    
  end
  
  def admin
    @tasks = Task.includes(:assignments).incomplete_first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end
  
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.unassigned

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @applicant = Applicant.new()

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        SiteMailer.new_task(@task).deliver
        format.html { redirect_to @task, notice: 'Thanks for submitting this task. You should receive an email confirmation shortly.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/applicants/_form.html.erb
<%= form_for(@applicant, html: { class: 'custom' }) do |f| %>
  
  <fieldset>
    
    <div class="row">
      <div class="columns">
        <div class="row">
          <div class="small-3 columns">
            <label for="applicant_name" class="right inline">Name</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :name, placeholder: 'Amy Ryan' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="applicant_email" class="right inline">Email</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :email, placeholder: 'amy.ryan@gmail.com' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="applicant_current_role" class="right inline">Current Role</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :current_role, placeholder: 'Student at Stanford University' %>
          </div>
        </div>
        <div class="row">
          <div class="small-12 columns">
            <label for="task_job_seeker" class="label_checkbox">
              Job seeker?
              <span class="check_box"><%= f.check_box :job_seeker %></span>
            </label>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="applicant_content" class="right inline">Why are you a good fit?</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_area :content, placeholder: "Tell us a bit about yourself" %>
          </div>
        </div>
        <%= f.hidden_field :task_id, value: @task.id %>
        <div class="row">
          <div class="small-3 columns"></div>
          <div class="small-9 columns">
            <span class="submit_waiting hide">Applying. Please wait. <%= image_tag 'loading.gif' %></span>
            <br/><br/>
          </div>
          <%= f.submit 'Submit application', class: 'button large expand', id: 'task_submit' %>
        </div>
      </div>
    </div> 
  </fieldset>
<% end %>

<script>

  (function(){

    $('form').on('keyup', 'textarea', function(){
       var ele = this;
       ele.style.height = 'auto';
       var height = $(this).css('height').replace('px', '');
       var newHeight = (ele.scrollHeight > height ? ele.scrollHeight : height);
       ele.style.height = newHeight.toString() + 'px';
    });
    
    $('form').on('submit', function(){
      
      $('span.submit_waiting').slideDown();
      
    });
    
  })();

</script>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<h1>Listing applicants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Current role</th>
    <th>Job seeker</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applicants.each do |applicant| %>
  <tr>
    <td><%= applicant.name %></td>
    <td><%= applicant.email %></td>
    <td><%= applicant.current_role %></td>
    <td><%= applicant.job_seeker %></td>
    <td><%= applicant.content %></td>
    <td><%= link_to 'Show', applicant %></td>
    <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
    <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @applicant.name %>
</p>

<p>
  <b>Email:</b>
  <%= @applicant.email %>
</p>

<p>
  <b>Current role:</b>
  <%= @applicant.current_role %>
</p>

<p>
  <b>Job seeker:</b>
  <%= @applicant.job_seeker %>
</p>

<p>
  <b>Content:</b>
  <%= @applicant.content %>
</p>


<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>

app/views/assignments/profile.html.erb
<div class="row projects">
	<div class="large-12 columns">
	  <h2 class="projects_header"><%= link_to @assignment.task.title, @assignment.task %></h2>

    <p>Organization | <%= link_to @assignment.task.organization_name, @assignment.task.organization_url %></p>
    <p>Deadline | <%= @assignment.task.formatted_deadline %></p>
    
    <div class="large-7 columns">
      <div class="task_detail_container">  
        <p class="task_detail_header">Details:</p>
        <p><%= @assignment.task.details %></p>
      </div>
      <p>Applicant Name: <%= @assignment.applicant.name %> (<%= link_to @assignment.applicant.email, "mailto:#{@assignment.applicant.email}" %>)</p>
      <p>Current_role: <%= @assignment.applicant.current_role %></p>
      <p>Job seeker? <%= @assignment.applicant.formatted_job_seeker %></p>
      <p>Content: <%= @assignment.applicant.content %></p>
    </div>
        
	</div>
</div>

app/views/assignments/show.html.erb
<div class="row projects">
	<div class="large-12 columns">
	  <h2 class="projects_header"><%= @assignment.task.title %></h2>

    <p>Organization | <%= link_to @assignment.task.organization_name, @assignment.task.organization_url %></p>
    <p>Deadline | <%= @assignment.task.formatted_deadline %></p>
    
    <div class="large-7 columns">
      <div class="task_detail_container">  
        <p class="task_detail_header">Details:</p>
        <p><%= @assignment.task.details %></p>
      </div>
      <p>Assignment: <%= @assignment.applicant.name %> (<%= link_to @assignment.applicant.email, "mailto:#{@assignment.applicant.email}" %>)</p>
      
      <%= form_for(@assignment) do |f| %>
        <p>Rating: <%= f.text_field :rating, class: 'small-1 inline' %></p>
        <p>Review: <%= f.text_area :review %></p>
        
        <p>Completed? <%= f.check_box :completed, checked: @assignment.task.completed %></p>
        
        <%= f.submit nil, class: 'button' %>
      
      <% end %>
    </div>
        
	</div>
</div>


<script>

  (function(){
    
    $('form').on('keyup', 'textarea', function(){
       var ele = this;
       ele.style.height = 'auto';
       var height = $(this).css('height').replace('px', '');
       var newHeight = (ele.scrollHeight > height ? ele.scrollHeight : height);
       ele.style.height = newHeight.toString() + 'px';
    });    
    
  })()



</script>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
	
		<div class="row">
			<div class="twelve columns">
				<nav class="footer_nav">
					<ul>
						<li class="about_us"><%= link_to 'About Us', about_url %></li>
						<li><%= link_to 'Contact', 'mailto:unternship@gmail.com?subject=Hello' %></li>
					</ul>
				</nav>
			</div>
		</div>
	
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="container">	
		<div class="row">
			<div class="large-5 columns">
				<h2 class="logo">
				  <span class="logo_highlight">un</span>ternship</h2>
			</div>
			<div class="large-7 columns">
				<nav>
					<ul>
						<li><%= link_to 'Home', root_url %></li>
						<li><%= link_to 'Apply', tasks_url, class: 'center' %></li>
						<li><%= link_to 'Post', new_task_url %></li>
					</ul>
				</nav>
			</div>
		</div>
	
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || 'Unternship' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  
  <% unless action_name == 'home' %>
    <%= render 'layouts/header' %>
  <% end %>
  
  <div class="container">
    
    <div class="row large-12 columns">
      <% if flash[:error] %>
        <%= content_tag :div, :id => "flash_name", :class => "alert-box error" do %>
          <%= flash[:error] %>
        <% end %>
      <% end %>

      <% if flash[:notice] %>
        <%= content_tag :div, :id => "flash_name", :class => "alert-box success" do %>
          <%= flash[:notice] %>
        <% end %>
      <% end %>
    </div>
    
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<div class="row projects">
	<div class="large-12 columns">
	  <h2 class="projects_header">Our Story</h2>
    <p>We've spent the past 8 years founding and working with non-profits, impact investment funds and social enterprises around the world.  In the hundreds of Skype calls with friends and friends of friends seeking work in the social sector, we heard time and again the challenges people faced in finding meaningful work.  Simultaneously, our organizations were drowning in work and constantly looking for young talent.</p>
     <p>Unternship is an experiment to see if we can't channel more talent into the social sector, while transforming the way organizations approach non-core work and recruitment.</p>
     <h2 class="projects_header">Our Team</h2> 
     <p><%= link_to 'Emily Lutyens', 'http://www.linkedin.com/pub/emily-mochizuki-lutyens/3a/b3a/a63' %> is an MBA candidate at Berkeley’s Haas School of Business and has five years of experience working with social entrepreneurs and NGOs in Uganda, Mexico and South Africa.  <%= link_to 'Daniela Papi', 'http://www.linkedin.com/in/danielapapi' %> is the founder of PEPY Cambodia and PEPY Tours and recently completed her MBA at Oxford University as a Skoll Scholar.  <%= link_to 'Timothy Rann', 'http://www.linkedin.com/pub/tim-rann/8/1b1/646' %> has five years of experience leading social business start-ups and impact investing funds in Cambodia, Vietnam and Afghanistan.</p>
     <p>Our beta product was designed by <%= link_to 'LaunchPad Lab', 'http://launchpadlab.com/' %>, a web development shop in Chicago that helps startups make their ideas real by helping them craft high-quality web applications. We are working with co-founders, <%= link_to 'Brendan Hennessy', 'http://www.linkedin.com/in/brendanjhennessy' %> and <%= link_to 'Liz Sarb', 'http://lizsarb.com/' %>, who are both passionate about using good design for social good.</p>
	</div>
</div>

app/views/pages/admin.html.erb
<div class="row projects">
	<div class="large-12 columns">
	  <h2 class="projects_header">Current projects</h2>
    <table class="projects large-12">
      <thead>
        <tr>
          <th>Task</th>
          <th>Details</th>
          <th>Organization</th>
          <th>File</th>
          <th>Assignment</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task %></td>
        <td><%= task.details %></td>
        <td><%= task.organization_name %></td>
        <td><%= task.file_url ? link_to('File', task.file_url) : 'None' %></td>
        <% if task.assigned? %>
          <td><%= task.accepted_assignment.applicant.email %></td>
          <% if task.completed %>
            <td><%= link_to 'Completed', task.accepted_assignment %></td>
          <% else %>
            <td><%= link_to 'Details', task.accepted_assignment, class: 'button' %></td>
          <% end %>
        <% else %>
          <%= form_tag(assignment_update_url) do %>
          <td><%= collection_select :assignment, :id, task.assignments, :id, 'id_and_email', prompt: true %></td>
          <%= hidden_field_tag 'assignment[accepted]', value: true %>
          <td><%= submit_tag 'Assign', class: 'button' %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
      </tbody>
    </table>
    
	</div>
</div>

app/views/pages/home.html.erb
<div class="row">
	<div class="large-12 columns home_container">
		<h2 class="logo">
		  <span class="logo_highlight">un</span>ternship
		</h2>
		<div class="large-offset-2 large-8 columns">
	  <p class="message">
	    Connecting organizations that do good work with workers who want to do good.
	  </p>
	  <div class="large-5 columns">
	    <%= link_to 'Job seeker? Apply!', tasks_url, class: 'large button expand' %>
	  </div>
	  <div class="large-5 columns">
	    <%= link_to 'Talent seeker? Post!', new_task_url, class: 'large button expand' %>
	  </div>
	  </div>
	</div>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: { class: 'nine columns', multipart: true }) do |f| %>

  <fieldset>
  
    <div class="row">
      <div class="columns">
        <% if @task.errors.any? %>
          <div class="row">
            <div class="small-12 columns">
              <small class="error"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</small>
              <% @task.errors.full_messages.each do |msg| %>
                <p><%= msg %></p>
              <% end %>
            </div>
          </div>      
        <% end %>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_organization_name" class="right inline">Organization Name</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :organization_name, autofocus: true, placeholder: 'Oxfam' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_organization_url" class="right inline">Organization Website</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :organization_url, placeholder: 'http://www.oxfam.org/' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_contact_name" class="right inline">Contact Name</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :contact_name, placeholder: 'John Mikasa' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_email" class="right inline">Email</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :email, placeholder: 'john.mikasa@oxfam.org' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_organization_description" class="right inline">Organization Description</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_area :organization_description, placeholder: 'Please provide up to 5 sentence overview of what you do.', rows: 5 %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_title" class="right inline">Task Title</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :title, placeholder: 'HR Newsletter Design' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_deadline" class="right inline">Deadline</label>
          </div>
          <div class="small-9 columns">
            <%= f.text_field :deadline, placeholder: 'Select a date' %>
          </div>
        </div>

        <div class="row">
          <div class="small-3 columns">
            <label for="task_details" class="right inline">Task Details</label>
          </div>
          <div class="small-9 columns">
            <p>Please describe the final deliverable in detail and describe the process or tools the person should use.  Below you can upload one document the person might need or link to websites they might need to reference, so please describe how they might need to use those in completing the task.</p>
            <%= f.text_area :details, placeholder: 'Please enter some details about this task' %>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns">
            <label for="task_wufoo_link" class="right inline">Attach a file</label>
          </div>
          <div class="small-9 columns">
            <%= f.file_field :file %>
            <br/><br/><br/>
            <p>Once someone has chosen your project, you will be informed that your task has been assigned and the person will be able to download any documents you have uploaded. When the final deliverable has been submitted, it will be sent to the email address you provided above.  You will also receive a survey to rate the user's work and submit a minimum of a 1-sentence line of feedback.</p>
          </div>
        </div>
        <div class="row">
          <div class="small-3 columns"></div>
          <div class="small-9 columns">
            <span class="submit_waiting hide">Submitting your task. Please wait. <%= image_tag 'loading.gif' %></span>
            <br/><br/>
          </div>
        </div>
        <div class="row">
          <%= f.submit nil, class: 'button large expand', id: 'task_submit' %>
        </div>
      </div>  
  </fieldset>
<% end %>

<script>

  (function(){
    
    $('#task_deadline').datepicker({
      dateFormat: 'yy-mm-dd'
    });
    
    $('form').on('submit', function(){
      
      $('span.submit_waiting').slideDown();
      
    });
    
    $('form').on('keyup', 'textarea', function(){
       var ele = this;
       ele.style.height = 'auto';
       var height = $(this).css('height').replace('px', '');
       var newHeight = (ele.scrollHeight > height ? ele.scrollHeight : height);
       ele.style.height = newHeight.toString() + 'px';
    });
    
  })();




</script>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row projects">
	<div class="large-12 columns">
	  <h2 class="projects_header">Find a project</h2>
    <table class="projects large-12">
      <thead>
        <tr>
          <th>Task</th>
          <th>Details</th>
          <th>Organization</th>
          <th>Deadline</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.details %></td>
        <td><%= task.organization_name %></td>
        <td><%= task.formatted_deadline %></td>
        <td><%= link_to 'Details', task, class: 'button' %></td>
      </tr>
    <% end %>
      </tbody>
    </table>
    
	</div>
</div>

app/views/tasks/new.html.erb
<div class="row">
	<div class="twelve columns">
    <h2 class="projects_header">Add a new task</h2>
    
    <%= render 'form' %>

  </div>
</div>

app/views/tasks/show.html.erb
<div class="row projects">
	<div class="large-12 columns">
	  <h2 class="projects_header"><%= @task.title %></h2>

    <p>Organization | <%= link_to @task.organization_name, @task.formated_organization_url %></p>
    <p>Deadline | <%= @task.formatted_deadline %></p>
    
    <div class="large-7 columns">
      <div class="task_detail_container">  
        <p class="task_detail_header">Details:</p>
        <p><%= @task.details %></p>
      </div>
      <p><%= link_to 'Apply now!', '#', class: 'button right', id: 'apply' %></p>
      <p><%= link_to 'Back to list', tasks_url, class: 'button secondary' %></p>
      
      <div class="applicant_container hide columns">
        <h2 class="projects_header">Glad you're interested.</h2>
        <p class="green">Please enter some information about yourself.</p>
        <%= render 'applicants/form' %>
      </div>
      
    </div>
        
	</div>
</div>


<script>

  (function(){
    
    $('a#apply').on('click', function(e){
      
      $('div.applicant_container').slideDown();
      $('input#applicant_name').focus();
      e.preventDefault();
    })
    
    
  })()



</script>